### ISSUE TITLE
warning in new ruby

### ISSUE THREAD

**Issue by tuwilof** [funbox/esplanade#26]
after update ruby to 2.7.1 (rails 6.0.3.1) warning appeared

/Users/dima/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/esplanade-1.5.0/lib/esplanade/request/error.rb:26: warning: The called method `initialize' is defined here

**Comment by StoneGod** [comment]
You should change `super(to_hash)` to `super(**to_hash)`

**Comment by tuwilof** [comment]
oops, warning because of monkey patch
