### ISSUE TITLE
Fix middleware constructor arguments

### ISSUE THREAD

**Issue by GolovkoStepan** [funbox/esplanade#39]
Must be removed from constructor arguments apib_path as it is no longer used in Tomograph::Tomogram.
It would also be nice to add support for crafter_yaml_path.

**Comment by tuwilof** [comment]
ready, we push new versions 1.7.0 fix improvement 😎

**Comment by GolovkoStepan** [comment]
> ready, we push new versions 1.7.0 fix improvement 😎

cool, thanks!
